<?php

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        DB::table('country')->delete();

        DB::table('country')->insert(array('id' => 'AU', 'name' => 'Австралия'));
        DB::table('country')->insert(array('id' => 'AT', 'name' => 'Австрия'));
        DB::table('country')->insert(array('id' => 'AZ', 'name' => 'Азербайджан'));
        DB::table('country')->insert(array('id' => 'AX', 'name' => 'Аландские о-ва'));
        DB::table('country')->insert(array('id' => 'AL', 'name' => 'Албания'));
        DB::table('country')->insert(array('id' => 'DZ', 'name' => 'Алжир'));
        DB::table('country')->insert(array('id' => 'AS', 'name' => 'Американское Самоа'));
        DB::table('country')->insert(array('id' => 'AI', 'name' => 'Ангилья'));
        DB::table('country')->insert(array('id' => 'AO', 'name' => 'Ангола'));
        DB::table('country')->insert(array('id' => 'AD', 'name' => 'Андорра'));
        DB::table('country')->insert(array('id' => 'AQ', 'name' => 'Антарктида'));
        DB::table('country')->insert(array('id' => 'AG', 'name' => 'Антигуа и Барбуда'));
        DB::table('country')->insert(array('id' => 'AR', 'name' => 'Аргентина'));
        DB::table('country')->insert(array('id' => 'AM', 'name' => 'Армения'));
        DB::table('country')->insert(array('id' => 'AW', 'name' => 'Аруба'));
        DB::table('country')->insert(array('id' => 'AF', 'name' => 'Афганистан'));
        DB::table('country')->insert(array('id' => 'BS', 'name' => 'Багамские о-ва'));
        DB::table('country')->insert(array('id' => 'BD', 'name' => 'Бангладеш'));
        DB::table('country')->insert(array('id' => 'BB', 'name' => 'Барбадос'));
        DB::table('country')->insert(array('id' => 'BH', 'name' => 'Бахрейн'));
        DB::table('country')->insert(array('id' => 'BY', 'name' => 'Беларусь'));
        DB::table('country')->insert(array('id' => 'BZ', 'name' => 'Белиз'));
        DB::table('country')->insert(array('id' => 'BE', 'name' => 'Бельгия'));
        DB::table('country')->insert(array('id' => 'BJ', 'name' => 'Бенин'));
        DB::table('country')->insert(array('id' => 'BM', 'name' => 'Бермудские о-ва'));
        DB::table('country')->insert(array('id' => 'BG', 'name' => 'Болгария'));
        DB::table('country')->insert(array('id' => 'BO', 'name' => 'Боливия'));
        DB::table('country')->insert(array('id' => 'BA', 'name' => 'Босния и Герцеговина'));
        DB::table('country')->insert(array('id' => 'BW', 'name' => 'Ботсвана'));
        DB::table('country')->insert(array('id' => 'BR', 'name' => 'Бразилия'));
        DB::table('country')->insert(array('id' => 'IO', 'name' => 'Британская территория в Индийском океане'));
        DB::table('country')->insert(array('id' => 'VG', 'name' => 'Британские Виргинские о-ва'));
        DB::table('country')->insert(array('id' => 'BN', 'name' => 'Бруней Даруссалам'));
        DB::table('country')->insert(array('id' => 'BF', 'name' => 'Буркина Фасо'));
        DB::table('country')->insert(array('id' => 'BI', 'name' => 'Бурунди'));
        DB::table('country')->insert(array('id' => 'BT', 'name' => 'Бутан'));
        DB::table('country')->insert(array('id' => 'VU', 'name' => 'Вануату'));
        DB::table('country')->insert(array('id' => 'VA', 'name' => 'Ватикан'));
        DB::table('country')->insert(array('id' => 'GB', 'name' => 'Великобритания'));
        DB::table('country')->insert(array('id' => 'HU', 'name' => 'Венгрия'));
        DB::table('country')->insert(array('id' => 'VE', 'name' => 'Венесуэла'));
        DB::table('country')->insert(array('id' => 'VI', 'name' => 'Виргинские о-ва (США)'));
        DB::table('country')->insert(array('id' => 'UM', 'name' => 'Внешние малые острова (США)'));
        DB::table('country')->insert(array('id' => 'QO', 'name' => 'Внешняя Океания'));
        DB::table('country')->insert(array('id' => 'TL', 'name' => 'Восточный Тимор'));
        DB::table('country')->insert(array('id' => 'VN', 'name' => 'Вьетнам'));
        DB::table('country')->insert(array('id' => 'GA', 'name' => 'Габон'));
        DB::table('country')->insert(array('id' => 'HT', 'name' => 'Гаити'));
        DB::table('country')->insert(array('id' => 'GY', 'name' => 'Гайана'));
        DB::table('country')->insert(array('id' => 'GM', 'name' => 'Гамбия'));
        DB::table('country')->insert(array('id' => 'GH', 'name' => 'Гана'));
        DB::table('country')->insert(array('id' => 'GP', 'name' => 'Гваделупа'));
        DB::table('country')->insert(array('id' => 'GT', 'name' => 'Гватемала'));
        DB::table('country')->insert(array('id' => 'GN', 'name' => 'Гвинея'));
        DB::table('country')->insert(array('id' => 'GW', 'name' => 'Гвинея-Бисау'));
        DB::table('country')->insert(array('id' => 'DE', 'name' => 'Германия'));
        DB::table('country')->insert(array('id' => 'GG', 'name' => 'Гернси'));
        DB::table('country')->insert(array('id' => 'GI', 'name' => 'Гибралтар'));
        DB::table('country')->insert(array('id' => 'HN', 'name' => 'Гондурас'));
        DB::table('country')->insert(array('id' => 'HK', 'name' => 'Гонконг (особый район)'));
        DB::table('country')->insert(array('id' => 'GD', 'name' => 'Гренада'));
        DB::table('country')->insert(array('id' => 'GL', 'name' => 'Гренландия'));
        DB::table('country')->insert(array('id' => 'GR', 'name' => 'Греция'));
        DB::table('country')->insert(array('id' => 'GE', 'name' => 'Грузия'));
        DB::table('country')->insert(array('id' => 'GU', 'name' => 'Гуам'));
        DB::table('country')->insert(array('id' => 'DK', 'name' => 'Дания'));
        DB::table('country')->insert(array('id' => 'CD', 'name' => 'Демократическая Республика Конго'));
        DB::table('country')->insert(array('id' => 'JE', 'name' => 'Джерси'));
        DB::table('country')->insert(array('id' => 'DJ', 'name' => 'Джибути'));
        DB::table('country')->insert(array('id' => 'DG', 'name' => 'Диего-Гарсия'));
        DB::table('country')->insert(array('id' => 'DM', 'name' => 'Доминика'));
        DB::table('country')->insert(array('id' => 'DO', 'name' => 'Доминиканская Республика'));
        DB::table('country')->insert(array('id' => 'EU', 'name' => 'Европейский союз'));
        DB::table('country')->insert(array('id' => 'EG', 'name' => 'Египет'));
        DB::table('country')->insert(array('id' => 'ZM', 'name' => 'Замбия'));
        DB::table('country')->insert(array('id' => 'EH', 'name' => 'Западная Сахара'));
        DB::table('country')->insert(array('id' => 'ZW', 'name' => 'Зимбабве'));
        DB::table('country')->insert(array('id' => 'IL', 'name' => 'Израиль'));
        DB::table('country')->insert(array('id' => 'IN', 'name' => 'Индия'));
        DB::table('country')->insert(array('id' => 'ID', 'name' => 'Индонезия'));
        DB::table('country')->insert(array('id' => 'JO', 'name' => 'Иордания'));
        DB::table('country')->insert(array('id' => 'IQ', 'name' => 'Ирак'));
        DB::table('country')->insert(array('id' => 'IR', 'name' => 'Иран'));
        DB::table('country')->insert(array('id' => 'IE', 'name' => 'Ирландия'));
        DB::table('country')->insert(array('id' => 'IS', 'name' => 'Исландия'));
        DB::table('country')->insert(array('id' => 'ES', 'name' => 'Испания'));
        DB::table('country')->insert(array('id' => 'IT', 'name' => 'Италия'));
        DB::table('country')->insert(array('id' => 'YE', 'name' => 'Йемен'));
        DB::table('country')->insert(array('id' => 'KZ', 'name' => 'Казахстан'));
        DB::table('country')->insert(array('id' => 'KY', 'name' => 'Каймановы острова'));
        DB::table('country')->insert(array('id' => 'KH', 'name' => 'Камбоджа'));
        DB::table('country')->insert(array('id' => 'CM', 'name' => 'Камерун'));
        DB::table('country')->insert(array('id' => 'CA', 'name' => 'Канада'));
        DB::table('country')->insert(array('id' => 'IC', 'name' => 'Канарские о-ва'));
        DB::table('country')->insert(array('id' => 'QA', 'name' => 'Катар'));
        DB::table('country')->insert(array('id' => 'KE', 'name' => 'Кения'));
        DB::table('country')->insert(array('id' => 'CY', 'name' => 'Кипр'));
        DB::table('country')->insert(array('id' => 'KG', 'name' => 'Киргизия'));
        DB::table('country')->insert(array('id' => 'KI', 'name' => 'Кирибати'));
        DB::table('country')->insert(array('id' => 'CN', 'name' => 'Китай'));
        DB::table('country')->insert(array('id' => 'CC', 'name' => 'Кокосовые о-ва'));
        DB::table('country')->insert(array('id' => 'CO', 'name' => 'Колумбия'));
        DB::table('country')->insert(array('id' => 'KM', 'name' => 'Коморские о-ва'));
        DB::table('country')->insert(array('id' => 'CG', 'name' => 'Конго'));
        DB::table('country')->insert(array('id' => 'CR', 'name' => 'Коста-Рика'));
        DB::table('country')->insert(array('id' => 'CI', 'name' => 'Кот д’Ивуар'));
        DB::table('country')->insert(array('id' => 'CU', 'name' => 'Куба'));
        DB::table('country')->insert(array('id' => 'KW', 'name' => 'Кувейт'));
        DB::table('country')->insert(array('id' => 'LA', 'name' => 'Лаос'));
        DB::table('country')->insert(array('id' => 'LV', 'name' => 'Латвия'));
        DB::table('country')->insert(array('id' => 'LS', 'name' => 'Лесото'));
        DB::table('country')->insert(array('id' => 'LR', 'name' => 'Либерия'));
        DB::table('country')->insert(array('id' => 'LB', 'name' => 'Ливан'));
        DB::table('country')->insert(array('id' => 'LY', 'name' => 'Ливия'));
        DB::table('country')->insert(array('id' => 'LT', 'name' => 'Литва'));
        DB::table('country')->insert(array('id' => 'LI', 'name' => 'Лихтенштейн'));
        DB::table('country')->insert(array('id' => 'LU', 'name' => 'Люксембург'));
        DB::table('country')->insert(array('id' => 'MU', 'name' => 'Маврикий'));
        DB::table('country')->insert(array('id' => 'MR', 'name' => 'Мавритания'));
        DB::table('country')->insert(array('id' => 'MG', 'name' => 'Мадагаскар'));
        DB::table('country')->insert(array('id' => 'YT', 'name' => 'Майотта'));
        DB::table('country')->insert(array('id' => 'MO', 'name' => 'Макао (особый район)'));
        DB::table('country')->insert(array('id' => 'MK', 'name' => 'Македония'));
        DB::table('country')->insert(array('id' => 'MW', 'name' => 'Малави'));
        DB::table('country')->insert(array('id' => 'MY', 'name' => 'Малайзия'));
        DB::table('country')->insert(array('id' => 'ML', 'name' => 'Мали'));
        DB::table('country')->insert(array('id' => 'MV', 'name' => 'Мальдивские о-ва'));
        DB::table('country')->insert(array('id' => 'MT', 'name' => 'Мальта'));
        DB::table('country')->insert(array('id' => 'MA', 'name' => 'Марокко'));
        DB::table('country')->insert(array('id' => 'MQ', 'name' => 'Мартиника'));
        DB::table('country')->insert(array('id' => 'MH', 'name' => 'Маршалловы о-ва'));
        DB::table('country')->insert(array('id' => 'MX', 'name' => 'Мексика'));
        DB::table('country')->insert(array('id' => 'MZ', 'name' => 'Мозамбик'));
        DB::table('country')->insert(array('id' => 'MD', 'name' => 'Молдова'));
        DB::table('country')->insert(array('id' => 'MC', 'name' => 'Монако'));
        DB::table('country')->insert(array('id' => 'MN', 'name' => 'Монголия'));
        DB::table('country')->insert(array('id' => 'MS', 'name' => 'Монтсеррат'));
        DB::table('country')->insert(array('id' => 'MM', 'name' => 'Мьянма'));
        DB::table('country')->insert(array('id' => 'NA', 'name' => 'Намибия'));
        DB::table('country')->insert(array('id' => 'NR', 'name' => 'Науру'));
        DB::table('country')->insert(array('id' => 'NP', 'name' => 'Непал'));
        DB::table('country')->insert(array('id' => 'NE', 'name' => 'Нигер'));
        DB::table('country')->insert(array('id' => 'NG', 'name' => 'Нигерия'));
        DB::table('country')->insert(array('id' => 'AN', 'name' => 'Нидерландские Антильские о-ва'));
        DB::table('country')->insert(array('id' => 'NL', 'name' => 'Нидерланды'));
        DB::table('country')->insert(array('id' => 'NI', 'name' => 'Никарагуа'));
        DB::table('country')->insert(array('id' => 'NU', 'name' => 'Ниуе'));
        DB::table('country')->insert(array('id' => 'NZ', 'name' => 'Новая Зеландия'));
        DB::table('country')->insert(array('id' => 'NC', 'name' => 'Новая Каледония'));
        DB::table('country')->insert(array('id' => 'NO', 'name' => 'Норвегия'));
        DB::table('country')->insert(array('id' => 'AE', 'name' => 'ОАЭ'));
        DB::table('country')->insert(array('id' => 'OM', 'name' => 'Оман'));
        DB::table('country')->insert(array('id' => 'BV', 'name' => 'Остров Буве'));
        DB::table('country')->insert(array('id' => 'AC', 'name' => 'Остров Вознесения'));
        DB::table('country')->insert(array('id' => 'CP', 'name' => 'Остров Клиппертон'));
        DB::table('country')->insert(array('id' => 'IM', 'name' => 'Остров Мэн'));
        DB::table('country')->insert(array('id' => 'NF', 'name' => 'Остров Норфолк'));
        DB::table('country')->insert(array('id' => 'CX', 'name' => 'Остров Рождества'));
        DB::table('country')->insert(array('id' => 'BL', 'name' => 'Остров Святого Бартоломея'));
        DB::table('country')->insert(array('id' => 'MF', 'name' => 'Остров Святого Мартина'));
        DB::table('country')->insert(array('id' => 'SH', 'name' => 'Остров Святой Елены'));
        DB::table('country')->insert(array('id' => 'CV', 'name' => 'Острова Зеленого Мыса'));
        DB::table('country')->insert(array('id' => 'CK', 'name' => 'Острова Кука'));
        DB::table('country')->insert(array('id' => 'TC', 'name' => 'Острова Тёркс и Кайкос'));
        DB::table('country')->insert(array('id' => 'HM', 'name' => 'Острова Херд и Макдональд'));
        DB::table('country')->insert(array('id' => 'PK', 'name' => 'Пакистан'));
        DB::table('country')->insert(array('id' => 'PW', 'name' => 'Палау'));
        DB::table('country')->insert(array('id' => 'PS', 'name' => 'Палестинские территории'));
        DB::table('country')->insert(array('id' => 'PA', 'name' => 'Панама'));
        DB::table('country')->insert(array('id' => 'PG', 'name' => 'Папуа – Новая Гвинея'));
        DB::table('country')->insert(array('id' => 'PY', 'name' => 'Парагвай'));
        DB::table('country')->insert(array('id' => 'PE', 'name' => 'Перу'));
        DB::table('country')->insert(array('id' => 'PN', 'name' => 'Питкэрн'));
        DB::table('country')->insert(array('id' => 'PL', 'name' => 'Польша'));
        DB::table('country')->insert(array('id' => 'PT', 'name' => 'Португалия'));
        DB::table('country')->insert(array('id' => 'PR', 'name' => 'Пуэрто-Рико'));
        DB::table('country')->insert(array('id' => 'KR', 'name' => 'Республика Корея'));
        DB::table('country')->insert(array('id' => 'RE', 'name' => 'Реюньон'));
        DB::table('country')->insert(array('id' => 'RU', 'name' => 'Россия'));
        DB::table('country')->insert(array('id' => 'RW', 'name' => 'Руанда'));
        DB::table('country')->insert(array('id' => 'RO', 'name' => 'Румыния'));
        DB::table('country')->insert(array('id' => 'SV', 'name' => 'Сальвадор'));
        DB::table('country')->insert(array('id' => 'WS', 'name' => 'Самоа'));
        DB::table('country')->insert(array('id' => 'SM', 'name' => 'Сан-Марино'));
        DB::table('country')->insert(array('id' => 'ST', 'name' => 'Сан-Томе и Принсипи'));
        DB::table('country')->insert(array('id' => 'SA', 'name' => 'Саудовская Аравия'));
        DB::table('country')->insert(array('id' => 'SZ', 'name' => 'Свазиленд'));
        DB::table('country')->insert(array('id' => 'SJ', 'name' => 'Свальбард и Ян-Майен'));
        DB::table('country')->insert(array('id' => 'KP', 'name' => 'Северная Корея'));
        DB::table('country')->insert(array('id' => 'MP', 'name' => 'Северные Марианские о-ва'));
        DB::table('country')->insert(array('id' => 'SC', 'name' => 'Сейшельские о-ва'));
        DB::table('country')->insert(array('id' => 'PM', 'name' => 'Сен-Пьер и Микелон'));
        DB::table('country')->insert(array('id' => 'SN', 'name' => 'Сенегал'));
        DB::table('country')->insert(array('id' => 'VC', 'name' => 'Сент-Винсент и Гренадины'));
        DB::table('country')->insert(array('id' => 'KN', 'name' => 'Сент-Киттс и Невис'));
        DB::table('country')->insert(array('id' => 'LC', 'name' => 'Сент-Люсия'));
        DB::table('country')->insert(array('id' => 'RS', 'name' => 'Сербия'));
        DB::table('country')->insert(array('id' => 'CS', 'name' => 'Сербия и Черногория'));
        DB::table('country')->insert(array('id' => 'EA', 'name' => 'Сеута и Мелилья'));
        DB::table('country')->insert(array('id' => 'SG', 'name' => 'Сингапур'));
        DB::table('country')->insert(array('id' => 'SY', 'name' => 'Сирия'));
        DB::table('country')->insert(array('id' => 'SK', 'name' => 'Словакия'));
        DB::table('country')->insert(array('id' => 'SI', 'name' => 'Словения'));
        DB::table('country')->insert(array('id' => 'SB', 'name' => 'Соломоновы о-ва'));
        DB::table('country')->insert(array('id' => 'SO', 'name' => 'Сомали'));
        DB::table('country')->insert(array('id' => 'SD', 'name' => 'Судан'));
        DB::table('country')->insert(array('id' => 'SR', 'name' => 'Суринам'));
        DB::table('country')->insert(array('id' => 'US', 'name' => 'США'));
        DB::table('country')->insert(array('id' => 'SL', 'name' => 'Сьерра-Леоне'));
        DB::table('country')->insert(array('id' => 'TJ', 'name' => 'Таджикистан'));
        DB::table('country')->insert(array('id' => 'TH', 'name' => 'Таиланд'));
        DB::table('country')->insert(array('id' => 'TW', 'name' => 'Тайвань'));
        DB::table('country')->insert(array('id' => 'TZ', 'name' => 'Танзания'));
        DB::table('country')->insert(array('id' => 'TG', 'name' => 'Того'));
        DB::table('country')->insert(array('id' => 'TK', 'name' => 'Токелау'));
        DB::table('country')->insert(array('id' => 'TO', 'name' => 'Тонга'));
        DB::table('country')->insert(array('id' => 'TT', 'name' => 'Тринидад и Тобаго'));
        DB::table('country')->insert(array('id' => 'TA', 'name' => 'Тристан-да-Кунья'));
        DB::table('country')->insert(array('id' => 'TV', 'name' => 'Тувалу'));
        DB::table('country')->insert(array('id' => 'TN', 'name' => 'Тунис'));
        DB::table('country')->insert(array('id' => 'TM', 'name' => 'Туркменистан'));
        DB::table('country')->insert(array('id' => 'TR', 'name' => 'Турция'));
        DB::table('country')->insert(array('id' => 'UG', 'name' => 'Уганда'));
        DB::table('country')->insert(array('id' => 'UZ', 'name' => 'Узбекистан'));
        DB::table('country')->insert(array('id' => 'UA', 'name' => 'Украина'));
        DB::table('country')->insert(array('id' => 'WF', 'name' => 'Уоллис и Футуна'));
        DB::table('country')->insert(array('id' => 'UY', 'name' => 'Уругвай'));
        DB::table('country')->insert(array('id' => 'FO', 'name' => 'Фарерские о-ва'));
        DB::table('country')->insert(array('id' => 'FM', 'name' => 'Федеративные Штаты Микронезии'));
        DB::table('country')->insert(array('id' => 'FJ', 'name' => 'Фиджи'));
        DB::table('country')->insert(array('id' => 'PH', 'name' => 'Филиппины'));
        DB::table('country')->insert(array('id' => 'FI', 'name' => 'Финляндия'));
        DB::table('country')->insert(array('id' => 'FK', 'name' => 'Фолклендские о-ва'));
        DB::table('country')->insert(array('id' => 'FR', 'name' => 'Франция'));
        DB::table('country')->insert(array('id' => 'GF', 'name' => 'Французская Гвиана'));
        DB::table('country')->insert(array('id' => 'PF', 'name' => 'Французская Полинезия'));
        DB::table('country')->insert(array('id' => 'TF', 'name' => 'Французские Южные Территории'));
        DB::table('country')->insert(array('id' => 'HR', 'name' => 'Хорватия'));
        DB::table('country')->insert(array('id' => 'CF', 'name' => 'ЦАР'));
        DB::table('country')->insert(array('id' => 'TD', 'name' => 'Чад'));
        DB::table('country')->insert(array('id' => 'ME', 'name' => 'Черногория'));
        DB::table('country')->insert(array('id' => 'CZ', 'name' => 'Чехия'));
        DB::table('country')->insert(array('id' => 'CL', 'name' => 'Чили'));
        DB::table('country')->insert(array('id' => 'CH', 'name' => 'Швейцария'));
        DB::table('country')->insert(array('id' => 'SE', 'name' => 'Швеция'));
        DB::table('country')->insert(array('id' => 'LK', 'name' => 'Шри-Ланка'));
        DB::table('country')->insert(array('id' => 'EC', 'name' => 'Эквадор'));
        DB::table('country')->insert(array('id' => 'GQ', 'name' => 'Экваториальная Гвинея'));
        DB::table('country')->insert(array('id' => 'ER', 'name' => 'Эритрея'));
        DB::table('country')->insert(array('id' => 'EE', 'name' => 'Эстония'));
        DB::table('country')->insert(array('id' => 'ET', 'name' => 'Эфиопия'));
        DB::table('country')->insert(array('id' => 'ZA', 'name' => 'ЮАР'));
        DB::table('country')->insert(array('id' => 'GS', 'name' => 'Южная Джорджия и Южные Сандвичевы Острова'));
        DB::table('country')->insert(array('id' => 'JM', 'name' => 'Ямайка'));
        DB::table('country')->insert(array('id' => 'JP', 'name' => 'Япония'));

    }
}
